/**
 * @file NetLinx G4API.axi for tree-sitter
 * @license MIT
 */

module.exports = {
    constants: {
        // General constants
        g4api_axi_version: /G4API_AXI_VERSION/i,

        // Power
        btn_power: /BTN_POWER/i,

        // Volume controls
        btn_vol_up: /BTN_VOL_UP/i,
        btn_vol_down: /BTN_VOL_DN/i,
        btn_vol_mute: /BTN_VOL_MUTE/i,
        lvl_vol: /LVL_VOL/i,

        // Transport controls
        btn_play: /BTN_PLAY/i,
        btn_stop: /BTN_STOP/i,
        btn_pause: /BTN_PAUSE/i,
        btn_ffwd: /BTN_FFWD/i,
        btn_rew: /BTN_REW/i,
        btn_sfwd: /BTN_SFWD/i,
        btn_srev: /BTN_SREV/i,
        btn_record: /BTN_RECORD/i,
        btn_eject: /BTN_EJECT/i,
        btn_slow_fwd: /BTN_SLOW_FWD/i,
        btn_slow_rev: /BTN_SLOW_REV/i,
        btn_reset_counter: /BTN_RESET_COUNTER/i,
        btn_frame_fwd: /BTN_FRAME_FWD/i,
        btn_frame_rev: /BTN_FRAME_REV/i,
        btn_scan_speed: /BTN_SCAN_SPEED/i,
        btn_search_speed: /BTN_SEARCH_SPEED/i,

        // Numeric buttons
        btn_digit_0: /BTN_DIGIT_0/i,
        btn_digit_1: /BTN_DIGIT_1/i,
        btn_digit_2: /BTN_DIGIT_2/i,
        btn_digit_3: /BTN_DIGIT_3/i,
        btn_digit_4: /BTN_DIGIT_4/i,
        btn_digit_5: /BTN_DIGIT_5/i,
        btn_digit_6: /BTN_DIGIT_6/i,
        btn_digit_7: /BTN_DIGIT_7/i,
        btn_digit_8: /BTN_DIGIT_8/i,
        btn_digit_9: /BTN_DIGIT_9/i,
        btn_menu_plus_10: /BTN_MENU_PLUS_10/i,
        btn_menu_plus_100: /BTN_MENU_PLUS_100/i,
        btn_menu_plus_1000: /BTN_MENU_PLUS_1000/i,

        // Channel controls
        btn_chan_up: /BTN_CHAN_UP/i,
        btn_chan_dn: /BTN_CHAN_DN/i,

        // Menu navigation
        btn_menu_enter: /BTN_MENU_ENTER/i,
        btn_menu_cancel: /BTN_MENU_CANCEL/i,
        btn_menu_func: /BTN_MENU_FUNC/i,
        btn_menu_up: /BTN_MENU_UP/i,
        btn_menu_dn: /BTN_MENU_DN/i,
        btn_menu_lt: /BTN_MENU_LT/i,
        btn_menu_rt: /BTN_MENU_RT/i,
        btn_menu_select: /BTN_MENU_SELECT/i,
        btn_menu_exit: /BTN_MENU_EXIT/i,
        btn_menu_clear: /BTN_MENU_CLEAR/i,
        btn_menu_return: /BTN_MENU_RETURN/i,
        btn_menu_help: /BTN_MENU_HELP/i,
        btn_menu_display: /BTN_MENU_DISPLAY/i,
        btn_menu_info: /BTN_MENU_INFO/i,
        btn_menu_guide: /BTN_MENU_GUIDE/i,
        btn_menu_page_up: /BTN_MENU_PAGE_UP/i,
        btn_menu_page_dn: /BTN_MENU_PAGE_DN/i,
        btn_menu_favorites: /BTN_MENU_FAVORITES/i,
        btn_menu_audio: /BTN_MENU_AUDIO/i,
        btn_menu_subtitle: /BTN_MENU_SUBTITLE/i,
        btn_menu_title: /BTN_MENU_TITLE/i,
        btn_menu_top_menu: /BTN_MENU_TOP_MENU/i,
        btn_menu_angle: /BTN_MENU_ANGLE/i,
        btn_menu_back: /BTN_MENU_BACK/i,
        btn_menu_setup: /BTN_MENU_SETUP/i,
        btn_menu_continue: /BTN_MENU_CONTINUE/i,
        btn_menu_reset: /BTN_MENU_RESET/i,
        btn_menu_accept: /BTN_MENU_ACCEPT/i,
        btn_menu_reject: /BTN_MENU_REJECT/i,
        btn_menu_zoom: /BTN_MENU_ZOOM/i,
        btn_menu_sleep: /BTN_MENU_SLEEP/i,
        btn_menu_video: /BTN_MENU_VIDEO/i,
        btn_menu_live_tv: /BTN_MENU_LIVE_TV/i,
        btn_menu_advance: /BTN_MENU_ADVANCE/i,
        btn_menu_list: /BTN_MENU_LIST/i,
        btn_menu_dot: /BTN_MENU_DOT/i,
        btn_menu_pound: /BTN_MENU_POUND/i,
        btn_menu_asterisk: /BTN_MENU_ASTERISK/i,
        btn_menu_dash: /BTN_MENU_DASH/i,
        btn_menu_underscore: /BTN_MENU_UNDERSCORE/i,
        btn_menu_lt_paren: /BTN_MENU_LT_PAREN/i,
        btn_menu_rt_paren: /BTN_MENU_RT_PAREN/i,
        btn_menu_comma: /BTN_MENU_COMMA/i,
        btn_menu_hold: /BTN_MENU_HOLD/i,
        btn_menu_dial: /BTN_MENU_DIAL/i,
        btn_menu_flash: /BTN_MENU_FLASH/i,
        btn_menu_conference: /BTN_MENU_CONFERENCE/i,
        btn_menu_ab_repeat: /BTN_MENU_AB_REPEAT/i,
        btn_menu_thumbs_up: /BTN_MENU_THUMBS_UP/i,
        btn_menu_thumbs_dn: /BTN_MENU_THUMBS_DN/i,
        btn_menu_instant_replay: /BTN_MENU_INSTANT_REPLAY/i,
        btn_menu_record_speed: /BTN_MENU_RECORD_SPEED/i,
        btn_menu_program: /BTN_MENU_PROGRAM/i,
        btn_menu_tv_vcr: /BTN_MENU_TV_VCR/i,
        btn_menu_xm: /BTN_MENU_XM/i,
        btn_menu_fm: /BTN_MENU_FM/i,
        btn_menu_am: /BTN_MENU_AM/i,
        btn_menu_dimmer: /BTN_MENU_DIMMER/i,
        btn_menu_ppv: /BTN_MENU_PPV/i,
        btn_menu_function: /BTN_MENU_FUNCTION/i,

        // Source selection
        btn_source_tv1: /BTN_SOURCE_TV1/i,
        btn_source_video1: /BTN_SOURCE_VIDEO1/i,
        btn_source_video2: /BTN_SOURCE_VIDEO2/i,
        btn_source_video3: /BTN_SOURCE_VIDEO3/i,
        btn_source_tape1: /BTN_SOURCE_TAPE1/i,
        btn_source_tape2: /BTN_SOURCE_TAPE2/i,
        btn_source_cd1: /BTN_SOURCE_CD1/i,
        btn_source_tuner1: /BTN_SOURCE_TUNER1/i,
        btn_source_phono1: /BTN_SOURCE_PHONO1/i,
        btn_source_aux1: /BTN_SOURCE_AUX1/i,
        btn_source_cycle: /BTN_SOURCE_CYCLE/i,

        // Audio controls
        btn_balance_up: /BTN_BALANCE_UP/i,
        btn_balance_dn: /BTN_BALANCE_DN/i,
        btn_bass_up: /BTN_BASS_UP/i,
        btn_bass_dn: /BTN_BASS_DN/i,
        btn_treble_up: /BTN_TREBLE_UP/i,
        btn_treble_dn: /BTN_TREBLE_DN/i,
        btn_gain_up: /BTN_GAIN_UP/i,
        btn_gain_dn: /BTN_GAIN_DN/i,
        btn_gain_mute: /BTN_GAIN_MUTE/i,
        btn_loudness: /BTN_LOUDNESS/i,
        btn_surround_next: /BTN_SURROUND_NEXT/i,
        btn_surround_prev: /BTN_SURROUND_PREV/i,

        // Video/Display controls
        btn_aspect_ratio: /BTN_ASPECT_RATIO/i,
        btn_bright_up: /BTN_BRIGHT_UP/i,
        btn_bright_dn: /BTN_BRIGHT_DN/i,
        btn_color_up: /BTN_COLOR_UP/i,
        btn_color_dn: /BTN_COLOR_DN/i,
        btn_contrast_up: /BTN_CONTRAST_UP/i,
        btn_contrast_dn: /BTN_CONTRAST_DN/i,
        btn_sharp_up: /BTN_SHARP_UP/i,
        btn_sharp_dn: /BTN_SHARP_DN/i,
        btn_tint_up: /BTN_TINT_UP/i,
        btn_tint_dn: /BTN_TINT_DN/i,
        btn_pic_mute: /BTN_PIC_MUTE/i,
        btn_pic_freeze: /BTN_PIC_FREEZE/i,

        // PIP controls
        btn_pip: /BTN_PIP/i,
        btn_pip_pos: /BTN_PIP_POS/i,
        btn_pip_swap: /BTN_PIP_SWAP/i,

        // Tuner controls
        btn_tuner_band: /BTN_TUNER_BAND/i,
        btn_tuner_preset_group: /BTN_TUNER_PRESET_GROUP/i,
        btn_tuner_station_up: /BTN_TUNER_STATION_UP/i,
        btn_tuner_station_dn: /BTN_TUNER_STATION_DN/i,
        btn_tuner_scan_fwd: /BTN_TUNER_SCAN_FWD/i,
        btn_tuner_scan_rev: /BTN_TUNER_SCAN_REV/i,
        btn_tuner_seek_fwd: /BTN_TUNER_SEEK_FWD/i,
        btn_tuner_seek_rev: /BTN_TUNER_SEEK_REV/i,
        btn_tuner_prev: /BTN_TUNER_PREV/i,
        btn_cass_tape_side: /BTN_CASS_TAPE_SIDE/i,

        // Camera controls
        btn_tilt_up: /BTN_TILT_UP/i,
        btn_tilt_dn: /BTN_TILT_DN/i,
        btn_pan_up: /BTN_PAN_UP/i,
        btn_pan_dn: /BTN_PAN_DN/i,
        btn_pan_lt: /BTN_PAN_LT/i,
        btn_pan_rt: /BTN_PAN_RT/i,
        btn_zoom_in: /BTN_ZOOM_IN/i,
        btn_zoom_out: /BTN_ZOOM_OUT/i,
        btn_focus_near: /BTN_FOCUS_NEAR/i,
        btn_focus_far: /BTN_FOCUS_FAR/i,
        btn_auto_focus: /BTN_AUTO_FOCUS/i,
        btn_auto_iris: /BTN_AUTO_IRIS/i,
        btn_iris_open: /BTN_IRIS_OPEN/i,
        btn_iris_close: /BTN_IRIS_CLOSE/i,

        // Preset controls
        btn_vproj_preset_save: /BTN_VPROJ_PRESET_SAVE/i,
        btn_cam_preset_save: /BTN_CAM_PRESET_SAVE/i,
        btn_vol_preset_save: /BTN_VOL_PRESET_SAVE/i,
        btn_swt_take: /BTN_SWT_TAKE/i,
        btn_swt_preset_save: /BTN_SWT_PRESET_SAVE/i,
        btn_mixer_preset_save: /BTN_MIXER_PRESET_SAVE/i,
        btn_aproc_preset_save: /BTN_APROC_PRESET_SAVE/i,
        btn_vproc_preset_save: /BTN_VPROC_PRESET_SAVE/i,
        btn_multiwin_preset_save: /BTN_MULTIWIN_PRESET_SAVE/i,
        btn_vwall_config_save: /BTN_VWALL_CONFIG_SAVE/i,

        // Lamp/Power feedback
        btn_lamp_warming_fb: /BTN_LAMP_WARMING_FB/i,
        btn_lamp_cooling_fb: /BTN_LAMP_COOLING_FB/i,
        btn_lamp_power_fb: /BTN_LAMP_POWER_FB/i,

        // Security
        btn_sec_arm: /BTN_SEC_ARM/i,
        btn_sec_arm_home: /BTN_SEC_ARM_HOME/i,
        btn_sec_disarm: /BTN_SEC_DISARM/i,
        btn_sec_panic: /BTN_SEC_PANIC/i,
        btn_sec_police: /BTN_SEC_POLICE/i,
        btn_sec_fire: /BTN_SEC_FIRE/i,
        btn_sec_medical: /BTN_SEC_MEDICAL/i,
        btn_sec_arm_now: /BTN_SEC_ARM_NOW/i,
        btn_sec_arm_home_now: /BTN_SEC_ARM_HOME_NOW/i,
        btn_sec_pt_active: /BTN_SEC_PT_ACTIVE/i,
        btn_sec_pt_bypass: /BTN_SEC_PT_BYPASS/i,

        // HVAC controls
        btn_hvac_cool_up: /BTN_HVAC_COOL_UP/i,
        btn_hvac_cool_dn: /BTN_HVAC_COOL_DN/i,
        btn_hvac_heat_up: /BTN_HVAC_HEAT_UP/i,
        btn_hvac_heat_dn: /BTN_HVAC_HEAT_DN/i,
        btn_hvac_humidify_up: /BTN_HVAC_HUMIDIFY_UP/i,
        btn_hvac_humidify_dn: /BTN_HVAC_HUMIDIFY_DN/i,
        btn_hvac_dehumidify_up: /BTN_HVAC_DEHUMIDIFY_UP/i,
        btn_hvac_dehumidify_dn: /BTN_HVAC_DEHUMIDIFY_DN/i,
        btn_hvac_units: /BTN_HVAC_UNITS/i,
        btn_hvac_fan: /BTN_HVAC_FAN/i,
        btn_hvac_fan_status: /BTN_HVAC_FAN_STATUS/i,
        btn_hvac_humidify_state: /BTN_HVAC_HUMIDIFY_STATE/i,
        btn_hvac_state: /BTN_HVAC_STATE/i,

        // Pool/Spa controls
        btn_pool_heat: /BTN_POOL_HEAT/i,
        btn_spa_heat: /BTN_SPA_HEAT/i,
        btn_spa_jets: /BTN_SPA_JETS/i,
        btn_pool_heat_up: /BTN_POOL_HEAT_UP/i,
        btn_pool_heat_dn: /BTN_POOL_HEAT_DN/i,
        btn_spa_heat_up: /BTN_SPA_HEAT_UP/i,
        btn_spa_heat_dn: /BTN_SPA_HEAT_DN/i,
        btn_pool_pump_on: /BTN_POOL_PUMP_ON/i,
        btn_spa_pump_on: /BTN_SPA_PUMP_ON/i,
        btn_pool_light_on: /BTN_POOL_LIGHT_ON/i,
        btn_spa_light_on: /BTN_SPA_LIGHT_ON/i,
        btn_spa_blower_on: /BTN_SPA_BLOWER_ON/i,
        btn_pool_units: /BTN_POOL_UNITS/i,

        // Window/Wall controls
        btn_window_front: /BTN_WINDOW_FRONT/i,
        btn_window_back: /BTN_WINDOW_BACK/i,
        btn_window_forward: /BTN_WINDOW_FORWARD/i,
        btn_window_backward: /BTN_WINDOW_BACKWARD/i,
        btn_vwall_config_next: /BTN_VWALL_CONFIG_NEXT/i,
        btn_vwall_config_prev: /BTN_VWALL_CONFIG_PREV/i,

        // Motor controls
        btn_motor_stop: /BTN_MOTOR_STOP/i,
        btn_motor_open: /BTN_MOTOR_OPEN/i,
        btn_motor_close: /BTN_MOTOR_CLOSE/i,

        // Audio conferencer controls
        btn_aconf_privacy: /BTN_ACONF_PRIVACY/i,
        btn_aconf_train: /BTN_ACONF_TRAIN/i,
        btn_dial_redial: /BTN_DIAL_REDIAL/i,
        btn_dial_off_hook: /BTN_DIAL_OFF_HOOK/i,
        btn_dial_auto_answer: /BTN_DIAL_AUTO_ANSWER/i,
        btn_dial_audible_ring: /BTN_DIAL_AUDIBLE_RING/i,
        btn_phonebook_next: /BTN_PHONEBOOK_NEXT/i,
        btn_phonebook_prev: /BTN_PHONEBOOK_PREV/i,
        btn_phonebook_dial: /BTN_PHONEBOOK_DIAL/i,
        btn_vconf_privacy: /BTN_VCONF_PRIVACY/i,
        btn_vconf_train: /BTN_VCONF_TRAIN/i,

        // Mixer/Processor controls
        btn_mixer_xpoint_mute: /BTN_MIXER_XPOINT_MUTE/i,
        btn_mixer_xpoint_up: /BTN_MIXER_XPOINT_UP/i,
        btn_mixer_xpoint_dn: /BTN_MIXER_XPOINT_DN/i,
        btn_aproc_xpoint_up: /BTN_APROC_XPOINT_UP/i,
        btn_aproc_xpoint_dn: /BTN_APROC_XPOINT_DN/i,
        btn_aproc_xpoint_mute: /BTN_APROC_XPOINT_MUTE/i,

        // Switcher controls
        btn_swt_level_all: /BTN_SWT_LEVEL_ALL/i,
        btn_swt_level_video: /BTN_SWT_LEVEL_VIDEO/i,
        btn_swt_level_audio: /BTN_SWT_LEVEL_AUDIO/i,

        // Cable/Settop Box controls
        btn_cable_ab: /BTN_CABLE_AB/i,
        btn_cable_pc: /BTN_CABLE_PC/i,
        btn_cable_timer: /BTN_CABLE_TIMER/i,
        btn_cable_clock: /BTN_CABLE_CLOCK/i,
        btn_cable_alt: /BTN_CABLE_ALT/i,
        btn_cable_ippv: /BTN_CABLE_IPPV/i,
        btn_cable_credit: /BTN_CABLE_CREDIT/i,
        btn_cable_scan: /BTN_CABLE_SCAN/i,
        btn_cable_ce: /BTN_CABLE_CE/i,
        btn_cable_buy: /BTN_CABLE_BUY/i,
        btn_cable_dcr: /BTN_CABLE_DCR/i,

        // Disc controls
        btn_disc_next: /BTN_DISC_NEXT/i,
        btn_disc_prev: /BTN_DISC_PREV/i,
        btn_disc_chapter: /BTN_DISC_CHAPTER/i,
        btn_disc_dnr: /BTN_DISC_DNR/i,
        btn_disc_memory: /BTN_DISC_MEMORY/i,
        btn_disc_mode: /BTN_DISC_MODE/i,
        btn_disc_play_mode: /BTN_DISC_PLAY_MODE/i,
        btn_disc_search_mode: /BTN_DISC_SEARCH_MODE/i,
        btn_disc_time: /BTN_DISC_TIME/i,
        btn_disc_tray: /BTN_DISC_TRAY/i,
        btn_disc_random: /BTN_DISC_RANDOM/i,
        btn_disc_repeat: /BTN_DISC_REPEAT/i,

        // Slide projector controls
        btn_slide_next: /BTN_SLIDE_NEXT/i,
        btn_slide_prev: /BTN_SLIDE_PREV/i,

        // Document camera controls
        btn_doccam_light: /BTN_DOCCAM_LIGHT/i,

        // Weather controls
        btn_weather_force_reading: /BTN_WEATHER_FORCE_READING/i,
        btn_weather_units: /BTN_WEATHER_UNITS/i,

        // Media database controls
        btn_mediadb_next: /BTN_MEDIADB_NEXT/i,
        btn_mediadb_prev: /BTN_MEDIADB_PREV/i,
        btn_mediadb_select: /BTN_MEDIADB_SELECT/i,
        btn_mediadb_back: /BTN_MEDIADB_BACK/i,
        btn_mediadb_play: /BTN_MEDIADB_PLAY/i,
        btn_mediadb_search: /BTN_MEDIADB_SEARCH/i,
        btn_mediadb_search_all: /BTN_MEDIADB_SEARCH_ALL/i,
        btn_mediadb_search_artist: /BTN_MEDIADB_SEARCH_ARTIST/i,
        btn_mediadb_search_genre: /BTN_MEDIADB_SEARCH_GENRE/i,
        btn_mediadb_search_title: /BTN_MEDIADB_SEARCH_TITLE/i,
        btn_mediadb_search_keywords: /BTN_MEDIADB_SEARCH_KEYWORDS/i,
        btn_mediadb_search_bookmark: /BTN_MEDIADB_SEARCH_BOOKMARK/i,
        btn_mediadb_search_text: /BTN_MEDIADB_SEARCH_TEXT/i,
        btn_mediadb_return_all: /BTN_MEDIADB_RETURN_ALL/i,
        btn_mediadb_return_picture: /BTN_MEDIADB_RETURN_PICTURE/i,
        btn_mediadb_return_application: /BTN_MEDIADB_RETURN_APPLICATION/i,
        btn_mediadb_return_track: /BTN_MEDIADB_RETURN_TRACK/i,
        btn_mediadb_return_chapter: /BTN_MEDIADB_RETURN_CHAPTER/i,
        btn_mediadb_return_playlist: /BTN_MEDIADB_RETURN_PLAYLIST/i,
        btn_mediadb_return_bookmark: /BTN_MEDIADB_RETURN_BOOKMARK/i,
        btn_mediadb_return_disc: /BTN_MEDIADB_RETURN_DISC/i,
        btn_mediadb_return_audio: /BTN_MEDIADB_RETURN_AUDIO/i,
        btn_mediadb_return_video: /BTN_MEDIADB_RETURN_VIDEO/i,
        btn_mediadb_return_genre: /BTN_MEDIADB_RETURN_GENRE/i,
        btn_mediadb_return_artist: /BTN_MEDIADB_RETURN_ARTIST/i,
        btn_mediadb_return_station: /BTN_MEDIADB_RETURN_STATION/i,

        // UPS controls
        btn_ups_outlet_state_1: /BTN_UPS_OUTLET_STATE_1/i,
        btn_ups_outlet_state_2: /BTN_UPS_OUTLET_STATE_2/i,
        btn_ups_outlet_state_3: /BTN_UPS_OUTLET_STATE_3/i,
        btn_ups_outlet_state_4: /BTN_UPS_OUTLET_STATE_4/i,
        btn_ups_outlet_state_5: /BTN_UPS_OUTLET_STATE_5/i,
        btn_ups_outlet_state_6: /BTN_UPS_OUTLET_STATE_6/i,

        // Light controls
        btn_light_ramp_up: /BTN_LIGHT_RAMP_UP/i,
        btn_light_ramp_dn: /BTN_LIGHT_RAMP_DN/i,
        btn_light_element_1: /BTN_LIGHT_ELEMENT_1/i,
        btn_light_element_2: /BTN_LIGHT_ELEMENT_2/i,
        btn_light_element_3: /BTN_LIGHT_ELEMENT_3/i,
        btn_light_element_4: /BTN_LIGHT_ELEMENT_4/i,
        btn_light_element_5: /BTN_LIGHT_ELEMENT_5/i,
        btn_light_element_6: /BTN_LIGHT_ELEMENT_6/i,
        btn_light_element_7: /BTN_LIGHT_ELEMENT_7/i,
        btn_light_element_8: /BTN_LIGHT_ELEMENT_8/i,
        btn_light_element_9: /BTN_LIGHT_ELEMENT_9/i,
        btn_light_element_10: /BTN_LIGHT_ELEMENT_10/i,
        btn_light_element_11: /BTN_LIGHT_ELEMENT_11/i,
        btn_light_element_12: /BTN_LIGHT_ELEMENT_12/i,
        btn_light_element_13: /BTN_LIGHT_ELEMENT_13/i,
        btn_light_element_14: /BTN_LIGHT_ELEMENT_14/i,
        btn_light_element_15: /BTN_LIGHT_ELEMENT_15/i,
        btn_light_element_16: /BTN_LIGHT_ELEMENT_16/i,
        btn_light_element_17: /BTN_LIGHT_ELEMENT_17/i,
        btn_light_element_18: /BTN_LIGHT_ELEMENT_18/i,
        btn_light_element_19: /BTN_LIGHT_ELEMENT_19/i,
        btn_light_element_20: /BTN_LIGHT_ELEMENT_20/i,

        // LightSystem controls
        btn_lightsys_ramp_up: /BTN_LIGHTSYS_RAMP_UP/i,
        btn_lightsys_ramp_dn: /BTN_LIGHTSYS_RAMP_DN/i,
        btn_lightsys_element_1: /BTN_LIGHTSYS_ELEMENT_1/i,
        btn_lightsys_element_2: /BTN_LIGHTSYS_ELEMENT_2/i,
        btn_lightsys_element_3: /BTN_LIGHTSYS_ELEMENT_3/i,
        btn_lightsys_element_4: /BTN_LIGHTSYS_ELEMENT_4/i,
        btn_lightsys_element_5: /BTN_LIGHTSYS_ELEMENT_5/i,
        btn_lightsys_element_6: /BTN_LIGHTSYS_ELEMENT_6/i,
        btn_lightsys_element_7: /BTN_LIGHTSYS_ELEMENT_7/i,
        btn_lightsys_element_8: /BTN_LIGHTSYS_ELEMENT_8/i,
        btn_lightsys_element_9: /BTN_LIGHTSYS_ELEMENT_9/i,
        btn_lightsys_element_10: /BTN_LIGHTSYS_ELEMENT_10/i,
        btn_lightsys_element_11: /BTN_LIGHTSYS_ELEMENT_11/i,
        btn_lightsys_element_12: /BTN_LIGHTSYS_ELEMENT_12/i,
        btn_lightsys_element_13: /BTN_LIGHTSYS_ELEMENT_13/i,
        btn_lightsys_element_14: /BTN_LIGHTSYS_ELEMENT_14/i,
        btn_lightsys_element_15: /BTN_LIGHTSYS_ELEMENT_15/i,
        btn_lightsys_element_16: /BTN_LIGHTSYS_ELEMENT_16/i,
        btn_lightsys_element_17: /BTN_LIGHTSYS_ELEMENT_17/i,
        btn_lightsys_element_18: /BTN_LIGHTSYS_ELEMENT_18/i,
        btn_lightsys_element_19: /BTN_LIGHTSYS_ELEMENT_19/i,
        btn_lightsys_element_20: /BTN_LIGHTSYS_ELEMENT_20/i,

        // Levels
        lvl_balance: /LVL_BALANCE/i,
        lvl_bass: /LVL_BASS/i,
        lvl_treble: /LVL_TREBLE/i,
        lvl_gain: /LVL_GAIN/i,
        lvl_bright: /LVL_BRIGHT/i,
        lvl_color: /LVL_COLOR/i,
        lvl_contrast: /LVL_CONTRAST/i,
        lvl_sharp: /LVL_SHARP/i,
        lvl_tint: /LVL_TINT/i,
        lvl_light_level_x: /LVL_LIGHT_LEVEL_X/i,
        lvl_light_level_y: /LVL_LIGHT_LEVEL_Y/i,
        lvl_lightsys_level_x: /LVL_LIGHTSYS_LEVEL_X/i,
        lvl_lightsys_level_y: /LVL_LIGHTSYS_LEVEL_Y/i,
        lvl_mixer_xpoint_set: /LVL_MIXER_XPOINT_SET/i,
        lvl_aproc_xpoint_set: /LVL_APROC_XPOINT_SET/i,

        // Text fields
        txt_source_input: /TXT_SOURCE_INPUT/i,
        txt_tuner_station: /TXT_TUNER_STATION/i,
        txt_tuner_band: /TXT_TUNER_BAND/i,
        txt_aspect_ratio: /TXT_ASPECT_RATIO/i,
        txt_lamp_hours: /TXT_LAMP_HOURS/i,
        txt_lamp_cooldown: /TXT_LAMP_COOLDOWN/i,
        txt_lamp_warmup: /TXT_LAMP_WARMUP/i,
        txt_media_counter: /TXT_MEDIA_COUNTER/i,
        txt_tape_counter: /TXT_TAPE_COUNTER/i,
        txt_disc_counter: /TXT_DISC_COUNTER/i,
        txt_disc_track_counter: /TXT_DISC_TRACK_COUNTER/i,
        txt_current_media_info: /TXT_CURRENT_MEDIA_INFO/i,
        txt_dial_number: /TXT_DIAL_NUMBER/i,
        txt_dial_call_progress: /TXT_DIAL_CALL_PROGRESS/i,
        txt_phonebook_name: /TXT_PHONEBOOK_NAME/i,
        txt_phonebook_number: /TXT_PHONEBOOK_NUMBER/i,
        txt_phonebook_list_status: /TXT_PHONEBOOK_LIST_STATUS/i,
        txt_mediadb_search_cur_item: /TXT_MEDIADB_SEARCH_CUR_ITEM/i,
        txt_mediadb_search_text: /TXT_MEDIADB_SEARCH_TEXT/i,
        txt_mediadb_search: /TXT_MEDIADB_SEARCH/i,
        txt_mediadb_return: /TXT_MEDIADB_RETURN/i,
        txt_mediadb_list_status: /TXT_MEDIADB_LIST_STATUS/i,
        txt_sec_status: /TXT_SEC_STATUS/i,
        txt_sec_password: /TXT_SEC_PASSWORD/i,
        txt_hvac_state: /TXT_HVAC_STATE/i,
        txt_hvac_status: /TXT_HVAC_STATUS/i,
        txt_hvac_humid_state: /TXT_HVAC_HUMID_STATE/i,
        txt_hvac_humid_status: /TXT_HVAC_HUMID_STATUS/i,
        txt_hvac_cool: /TXT_HVAC_COOL/i,
        txt_hvac_heat: /TXT_HVAC_HEAT/i,
        txt_hvac_temp: /TXT_HVAC_TEMP/i,
        txt_hvac_outdoor_temp: /TXT_HVAC_OUTDOOR_TEMP/i,
        txt_hvac_humid: /TXT_HVAC_HUMID/i,
        txt_hvac_outdoor_humid: /TXT_HVAC_OUTDOOR_HUMID/i,
        txt_hvac_humidify: /TXT_HVAC_HUMIDIFY/i,
        txt_hvac_dehumidify: /TXT_HVAC_DEHUMIDIFY/i,
        txt_indoor_temp: /TXT_INDOOR_TEMP/i,
        txt_outdoor_temp: /TXT_OUTDOOR_TEMP/i,
        txt_indoor_humid: /TXT_INDOOR_HUMID/i,
        txt_outdoor_humid: /TXT_OUTDOOR_HUMID/i,
        txt_pool_setpoint: /TXT_POOL_SETPOINT/i,
        txt_spa_setpoint: /TXT_SPA_SETPOINT/i,
        txt_pool_temp: /TXT_POOL_TEMP/i,
        txt_spa_temp: /TXT_SPA_TEMP/i,
        txt_pool_heater: /TXT_POOL_HEATER/i,
        txt_spa_heater: /TXT_SPA_HEATER/i,
        txt_spa_jets: /TXT_SPA_JETS/i,
        txt_pool_heating: /TXT_POOL_HEATING/i,
        txt_spa_heating: /TXT_SPA_HEATING/i,
        txt_ups_status: /TXT_UPS_STATUS/i,
        txt_ups_backup_time: /TXT_UPS_BACKUP_TIME/i,
        txt_ups_alarm: /TXT_UPS_ALARM/i,

        // Video controls
        btn_menu_preview_input: /BTN_MENU_PREVIEW_INPUT/i,
        btn_menu_send_input: /BTN_MENU_SEND_INPUT/i,
        btn_menu_send_graphics: /BTN_MENU_SEND_GRAPHICS/i,

        // Weather text fields
        txt_weather_hi_temp: /TXT_WEATHER_HI_TEMP/i,
        txt_weather_lo_temp: /TXT_WEATHER_LO_TEMP/i,
        txt_weather_wind_chill: /TXT_WEATHER_WIND_CHILL/i,
        txt_weather_heat_index: /TXT_WEATHER_HEAT_INDEX/i,
        txt_weather_dewpoint: /TXT_WEATHER_DEWPOINT/i,
        txt_weather_bar_press: /TXT_WEATHER_BAR_PRESS/i,
        txt_weather_bar_trend: /TXT_WEATHER_BAR_TREND/i,
        txt_weather_condition: /TXT_WEATHER_CONDITION/i,
        txt_weather_rain_today: /TXT_WEATHER_RAIN_TODAY/i,
        txt_weather_rain_week: /TXT_WEATHER_RAIN_WEEK/i,
        txt_weather_rain_month: /TXT_WEATHER_RAIN_MONTH/i,
        txt_weather_rain_year: /TXT_WEATHER_RAIN_YEAR/i,
        txt_weather_alert: /TXT_WEATHER_ALERT/i,

        // Weather array text fields
        txt_weather_wind_info: /TXT_WEATHER_WIND_INFO/i,
        txt_weather_forecast_condition: /TXT_WEATHER_FORECAST_CONDITION/i,
        txt_weather_forecast_hi: /TXT_WEATHER_FORECAST_HI/i,
        txt_weather_forecast_lo: /TXT_WEATHER_FORECAST_LO/i,
        txt_weather_forecast_cop: /TXT_WEATHER_FORECAST_COP/i,

        // Video wall specific controls
        btn_vwall_config: /BTN_VWALL_CONFIG/i,
        txt_vwall_config: /TXT_VWALL_CONFIG/i,

        // Soft-map constants
        btn_tuner_preset: /BTN_TUNER_PRESET/i,
        btn_source_input: /BTN_SOURCE_INPUT/i,
        btn_preamp_surround: /BTN_PREAMP_SURROUND/i,

        // Deprecated constants for compatibility
        btn_light_preset: /BTN_LIGHT_PRESET/i,
        btn_dial_flash_hook: /BTN_DIAL_FLASH_HOOK/i,
        txt_disc_number: /TXT_DISC_NUMBER/i,
        txt_disc_duration: /TXT_DISC_DURATION/i,
        txt_disc_titles: /TXT_DISC_TITLES/i,
        txt_disc_tracks: /TXT_DISC_TRACKS/i,
        txt_disc_type: /TXT_DISC_TYPE/i,
        txt_disc_title_number: /TXT_DISC_TITLE_NUMBER/i,
        txt_disc_title_duration: /TXT_DISC_TITLE_DURATION/i,
        txt_disc_title_tracks: /TXT_DISC_TITLE_TRACKS/i,
        btn_doccam_lower_light_on: /BTN_DOCCAM_LOWER_LIGHT_ON/i,
        btn_doccam_upper_light_on: /BTN_DOCCAM_UPPER_LIGHT_ON/i,
        btn_hvac_hold_on: /BTN_HVAC_HOLD_ON/i,
        btn_hvac_lock_on: /BTN_HVAC_LOCK_ON/i,
        btn_mixer_take: /BTN_MIXER_TAKE/i,
        btn_loudness_on: /BTN_LOUDNESS_ON/i,
        txt_weather_wind_speed: /TXT_WEATHER_WIND_SPEED/i,
        txt_weather_wind_dir: /TXT_WEATHER_WIND_DIR/i,

        // Array constants - these represent arrays defined in the G4API
        btn_vproj_preset: /BTN_VPROJ_PRESET/i,
        btn_input_source: /BTN_INPUT_SOURCE/i,
        btn_input_source_group: /BTN_INPUT_SOURCE_GROUP/i,
        btn_disc_list: /BTN_DISC_LIST/i,
        btn_dial_list: /BTN_DIAL_LIST/i,
        btn_phonebook_list: /BTN_PHONEBOOK_LIST/i,
        btn_cam_preset: /BTN_CAM_PRESET/i,
        btn_mixer_preset: /BTN_MIXER_PRESET/i,
        btn_mixer_input: /BTN_MIXER_INPUT/i,
        btn_mixer_output: /BTN_MIXER_OUTPUT/i,
        btn_aproc_preset: /BTN_APROC_PRESET/i,
        btn_aproc_input: /BTN_APROC_INPUT/i,
        btn_aproc_output: /BTN_APROC_OUTPUT/i,
        btn_swt_preset: /BTN_SWT_PRESET/i,
        btn_swt_input: /BTN_SWT_INPUT/i,
        btn_swt_output: /BTN_SWT_OUTPUT/i,
        btn_mediadb_properties: /BTN_MEDIADB_PROPERTIES/i,
        btn_mediadb_list: /BTN_MEDIADB_LIST/i,
        btn_vol_preset: /BTN_VOL_PRESET/i,
        btn_multiwin_preset: /BTN_MULTIWIN_PRESET/i,
        btn_window_input: /BTN_WINDOW_INPUT/i,
        btn_light_element: /BTN_LIGHT_ELEMENT/i,
        btn_lightsys_element: /BTN_LIGHTSYS_ELEMENT/i,
        btn_pool_aux: /BTN_POOL_AUX/i,
        btn_ups_outlet_state: /BTN_UPS_OUTLET_STATE/i,
        btn_io_state: /BTN_IO_STATE/i,
        btn_relay_state: /BTN_RELAY_STATE/i,
        btn_keypad_button: /BTN_KEYPAD_BUTTON/i,

        // Text fields arrays
        txt_disc_info: /TXT_DISC_INFO/i,
        txt_title_info: /TXT_TITLE_INFO/i,
        txt_track_info: /TXT_TRACK_INFO/i,
        txt_track_properties: /TXT_TRACK_PROPERTIES/i,
        txt_track_values: /TXT_TRACK_VALUES/i,
        txt_disc_properties: /TXT_DISC_PROPERTIES/i,
        txt_disc_values: /TXT_DISC_VALUES/i,
        txt_disc_title_properties: /TXT_DISC_TITLE_PROPERTIES/i,
        txt_disc_title_values: /TXT_DISC_TITLE_VALUES/i,
        txt_decode_properties: /TXT_DECODE_PROPERTIES/i,
        txt_decode_values: /TXT_DECODE_VALUES/i,
        txt_encode_properties: /TXT_ENCODE_PROPERTIES/i,
        txt_encode_values: /TXT_ENCODE_VALUES/i,
        txt_input_source: /TXT_INPUT_SOURCE/i,
        txt_input_source_group: /TXT_INPUT_SOURCE_GROUP/i,
        txt_phonebook_list: /TXT_PHONEBOOK_LIST/i,
        txt_mediadb_properties: /TXT_MEDIADB_PROPERTIES/i,
        txt_mediadb_values: /TXT_MEDIADB_VALUES/i,
        txt_mediadb_list: /TXT_MEDIADB_LIST/i,
        txt_light_element_name: /TXT_LIGHT_ELEMENT_NAME/i,
        txt_lightsys_element_name: /TXT_LIGHTSYS_ELEMENT_NAME/i,

        // Media control buttons
        btn_media_random: /BTN_MEDIA_RANDOM/i,
        btn_media_repeat: /BTN_MEDIA_REPEAT/i,
    },
};
