/**
 * @file NetLinx SNAPI constants for tree-sitter
 * @license MIT
 */

module.exports = {
    // SNAPI Version
    snapi_axi_version: /SNAPI_AXI_VERSION/i,

    // Invalid Values
    invalid_number: /INVALID_NUMBER/i,
    invalid_string: /INVALID_STRING/i,
    invalid_enum: /INVALID_ENUM/i,

    // Limits
    duet_min_level_value: /DUET_MIN_LEVEL_VALUE/i,
    duet_max_level_value: /DUET_MAX_LEVEL_VALUE/i,

    // Channel Constants
    power: /POWER/i,
    digit_0: /DIGIT_0/i,
    digit_1: /DIGIT_1/i,
    digit_2: /DIGIT_2/i,
    digit_3: /DIGIT_3/i,
    digit_4: /DIGIT_4/i,
    digit_5: /DIGIT_5/i,
    digit_6: /DIGIT_6/i,
    digit_7: /DIGIT_7/i,
    digit_8: /DIGIT_8/i,
    digit_9: /DIGIT_9/i,
    menu_plus_10: /MENU_PLUS_10/i,
    menu_enter: /MENU_ENTER/i,
    vol_up: /VOL_UP/i,
    vol_up_fb: /VOL_UP_FB/i,
    vol_dn: /VOL_DN/i,
    vol_dn_fb: /VOL_DN_FB/i,
    vol_mute: /VOL_MUTE/i,
    pwr_on: /PWR_ON/i,
    pwr_off: /PWR_OFF/i,
    vol_preset: /VOL_PRESET/i,
    vol_mute_on: /VOL_MUTE_ON/i,
    vol_mute_fb: /VOL_MUTE_FB/i,
    device_communicating: /DEVICE_COMMUNICATING/i,
    data_initialized: /DATA_INITIALIZED/i,
    power_on: /POWER_ON/i,
    power_fb: /POWER_FB/i,

    // Menu Navigation
    menu_cancel: /MENU_CANCEL/i,
    menu_func: /MENU_FUNC/i,
    menu_up: /MENU_UP/i,
    menu_dn: /MENU_DN/i,
    menu_lt: /MENU_LT/i,
    menu_rt: /MENU_RT/i,
    menu_select: /MENU_SELECT/i,
    menu_exit: /MENU_EXIT/i,
    menu_up_lt: /MENU_UP_LT/i,
    menu_up_rt: /MENU_UP_RT/i,
    menu_dn_lt: /MENU_DN_LT/i,
    menu_dn_rt: /MENU_DN_RT/i,
    menu_video: /MENU_VIDEO/i,
    menu_thumbs_dn: /MENU_THUMBS_DN/i,
    menu_thumbs_up: /MENU_THUMBS_UP/i,
    menu_accept: /MENU_ACCEPT/i,
    menu_reject: /MENU_REJECT/i,
    menu_live_tv: /MENU_LIVE_TV/i,
    menu_sleep: /MENU_SLEEP/i,
    menu_ppv: /MENU_PPV/i,
    menu_function: /MENU_FUNCTION/i,
    menu_setup: /MENU_SETUP/i,
    menu_xm: /MENU_XM/i,
    menu_fm: /MENU_FM/i,
    menu_am: /MENU_AM/i,
    menu_clear: /MENU_CLEAR/i,
    menu_back: /MENU_BACK/i,
    menu_forward: /MENU_FORWARD/i,
    menu_advance: /MENU_ADVANCE/i,
    menu_dimmer: /MENU_DIMMER/i,
    menu_hold: /MENU_HOLD/i,
    menu_list: /MENU_LIST/i,
    menu_lt_paren: /MENU_LT_PAREN/i,
    menu_rt_paren: /MENU_RT_PAREN/i,
    menu_underscore: /MENU_UNDERSCORE/i,
    menu_dash: /MENU_DASH/i,
    menu_asterisk: /MENU_ASTERISK/i,
    menu_dot: /MENU_DOT/i,
    menu_pound: /MENU_POUND/i,
    menu_comma: /MENU_COMMA/i,
    menu_dial: /MENU_DIAL/i,
    menu_conference: /MENU_CONFERENCE/i,
    menu_plus_100: /MENU_PLUS_100/i,
    menu_plus_1000: /MENU_PLUS_1000/i,
    menu_display: /MENU_DISPLAY/i,
    menu_subtitle: /MENU_SUBTITLE/i,
    menu_info: /MENU_INFO/i,
    menu_favorites: /MENU_FAVORITES/i,
    menu_continue: /MENU_CONTINUE/i,
    menu_return: /MENU_RETURN/i,
    menu_guide: /MENU_GUIDE/i,
    menu_page_up: /MENU_PAGE_UP/i,
    menu_page_dn: /MENU_PAGE_DN/i,
    menu_deck_a_b: /MENU_DECK_A_B/i,
    menu_tv_vcr: /MENU_TV_VCR/i,
    menu_record_speed: /MENU_RECORD_SPEED/i,
    menu_program: /MENU_PROGRAM/i,
    menu_ab_repeat: /MENU_AB_REPEAT/i,
    menu_help: /MENU_HELP/i,
    menu_title: /MENU_TITLE/i,
    menu_top_menu: /MENU_TOP_MENU/i,
    menu_zoom: /MENU_ZOOM/i,
    menu_angle: /MENU_ANGLE/i,
    menu_audio: /MENU_AUDIO/i,
    menu_preview_input: /MENU_PREVIEW_INPUT/i,
    menu_send_input: /MENU_SEND_INPUT/i,
    menu_send_graphics: /MENU_SEND_GRAPHICS/i,
    menu_flash: /MENU_FLASH/i,
    menu_reset: /MENU_RESET/i,
    menu_instant_replay: /MENU_INSTANT_REPLAY/i,

    // Audio Processing
    audioproc_level_up: /AUDIOPROC_LEVEL_UP/i,
    audioproc_level_dn: /AUDIOPROC_LEVEL_DN/i,
    audioproc_state: /AUDIOPROC_STATE/i,
    audioproc_state_on: /AUDIOPROC_STATE_ON/i,
    audioproc_state_fb: /AUDIOPROC_STATE_FB/i,
    audioproc_preset: /AUDIOPROC_PRESET/i,
    audioproc_lvl: /AUDIOPROC_LVL/i,

    // Transport Controls
    play: /PLAY/i,
    stop: /STOP/i,
    pause: /PAUSE/i,
    ffwd: /FFWD/i,
    rew: /REW/i,
    sfwd: /SFWD/i,
    srev: /SREV/i,
    record: /RECORD/i,
    play_fb: /PLAY_FB/i,
    stop_fb: /STOP_FB/i,
    pause_fb: /PAUSE_FB/i,
    ffwd_fb: /FFWD_FB/i,
    rew_fb: /REW_FB/i,
    sfwd_fb: /SFWD_FB/i,
    srev_fb: /SREV_FB/i,
    record_fb: /RECORD_FB/i,

    // Audio Controls
    gain_up: /GAIN_UP/i,
    gain_dn: /GAIN_DN/i,
    gain_up_fb: /GAIN_UP_FB/i,
    gain_dn_fb: /GAIN_DN_FB/i,
    gain_mute: /GAIN_MUTE/i,
    gain_mute_on: /GAIN_MUTE_ON/i,
    gain_mute_fb: /GAIN_MUTE_FB/i,

    // Cassette Controls
    cass_reverse_play: /CASS_REVERSE_PLAY/i,
    cass_tape_side: /CASS_TAPE_SIDE/i,
    cass_tape_side_a: /CASS_TAPE_SIDE_A/i,
    cass_tape_side_a_fb: /CASS_TAPE_SIDE_A_FB/i,
    cass_tape_side_b: /CASS_TAPE_SIDE_B/i,
    cass_tape_side_b_fb: /CASS_TAPE_SIDE_B_FB/i,
    cass_record_mute: /CASS_RECORD_MUTE/i,
    cass_record_mute_on: /CASS_RECORD_MUTE_ON/i,
    cass_record_mute_fb: /CASS_RECORD_MUTE_FB/i,

    // Tape/Media Controls
    search_speed: /SEARCH_SPEED/i,
    eject: /EJECT/i,
    reset_counter: /RESET_COUNTER/i,
    tape_loaded_fb: /TAPE_LOADED_FB/i,
    record_lock_fb: /RECORD_LOCK_FB/i,
    slow_fwd: /SLOW_FWD/i,
    slow_rev: /SLOW_REV/i,
    slow_fwd_fb: /SLOW_FWD_FB/i,
    slow_rev_fb: /SLOW_REV_FB/i,

    // Conference Controls
    aconf_privacy: /ACONF_PRIVACY/i,
    aconf_privacy_on: /ACONF_PRIVACY_ON/i,
    aconf_privacy_fb: /ACONF_PRIVACY_FB/i,
    aconf_train: /ACONF_TRAIN/i,

    // Dialer Controls
    dial_redial: /DIAL_REDIAL/i,
    dial_off_hook: /DIAL_OFF_HOOK/i,
    dial_auto_answer: /DIAL_AUTO_ANSWER/i,
    dial_audible_ring: /DIAL_AUDIBLE_RING/i,
    dial_flash_hook: /DIAL_FLASH_HOOK/i,
    dial_off_hook_on: /DIAL_OFF_HOOK_ON/i,
    dial_off_hook_fb: /DIAL_OFF_HOOK_FB/i,
    dial_auto_answer_on: /DIAL_AUTO_ANSWER_ON/i,
    dial_auto_answer_fb: /DIAL_AUTO_ANSWER_FB/i,
    dial_audible_ring_on: /DIAL_AUDIBLE_RING_ON/i,
    dial_audible_ring_fb: /DIAL_AUDIBLE_RING_FB/i,

    // Levels
    vol_lvl: /VOL_LVL/i,
    gain_lvl: /GAIN_LVL/i,

    // Tuner Controls
    chan_up: /CHAN_UP/i,
    chan_dn: /CHAN_DN/i,
    tuner_band: /TUNER_BAND/i,
    tuner_preset_group: /TUNER_PRESET_GROUP/i,
    tuner_station_up: /TUNER_STATION_UP/i,
    tuner_station_dn: /TUNER_STATION_DN/i,
    tuner_scan_fwd: /TUNER_SCAN_FWD/i,
    tuner_scan_rev: /TUNER_SCAN_REV/i,
    tuner_seek_fwd: /TUNER_SEEK_FWD/i,
    tuner_seek_rev: /TUNER_SEEK_REV/i,
    tuner_osd: /TUNER_OSD/i,
    tuner_prev: /TUNER_PREV/i,

    // Camera Controls
    tilt_up: /TILT_UP/i,
    tilt_up_fb: /TILT_UP_FB/i,
    tilt_dn: /TILT_DN/i,
    tilt_dn_fb: /TILT_DN_FB/i,
    pan_lt: /PAN_LT/i,
    pan_lt_fb: /PAN_LT_FB/i,
    pan_rt: /PAN_RT/i,
    pan_rt_fb: /PAN_RT_FB/i,
    zoom_out: /ZOOM_OUT/i,
    zoom_out_fb: /ZOOM_OUT_FB/i,
    zoom_in: /ZOOM_IN/i,
    zoom_in_fb: /ZOOM_IN_FB/i,
    focus_near: /FOCUS_NEAR/i,
    focus_near_fb: /FOCUS_NEAR_FB/i,
    focus_far: /FOCUS_FAR/i,
    focus_far_fb: /FOCUS_FAR_FB/i,
    auto_focus_on: /AUTO_FOCUS_ON/i,
    auto_focus_fb: /AUTO_FOCUS_FB/i,
    auto_iris_on: /AUTO_IRIS_ON/i,
    auto_iris_fb: /AUTO_IRIS_FB/i,
    auto_focus: /AUTO_FOCUS/i,
    auto_iris: /AUTO_IRIS/i,
    iris_open: /IRIS_OPEN/i,
    iris_open_fb: /IRIS_OPEN_FB/i,
    iris_close: /IRIS_CLOSE/i,
    iris_close_fb: /IRIS_CLOSE_FB/i,
    cam_preset: /CAM_PRESET/i,

    // Camera Levels
    zoom_lvl: /ZOOM_LVL/i,
    focus_lvl: /FOCUS_LVL/i,
    iris_lvl: /IRIS_LVL/i,
    zoom_speed_lvl: /ZOOM_SPEED_LVL/i,
    focus_speed_lvl: /FOCUS_SPEED_LVL/i,
    iris_speed_lvl: /IRIS_SPEED_LVL/i,
    pan_lvl: /PAN_LVL/i,
    tilt_lvl: /TILT_LVL/i,
    pan_speed_lvl: /PAN_SPEED_LVL/i,
    tilt_speed_lvl: /TILT_SPEED_LVL/i,

    // Media Controls
    media_random: /MEDIA_RANDOM/i,
    media_repeat: /MEDIA_REPEAT/i,
    media_random_disc_on: /MEDIA_RANDOM_DISC_ON/i,
    media_random_disc_fb: /MEDIA_RANDOM_DISC_FB/i,
    media_random_all_on: /MEDIA_RANDOM_ALL_ON/i,
    media_random_all_fb: /MEDIA_RANDOM_ALL_FB/i,
    media_random_off_on: /MEDIA_RANDOM_OFF_ON/i,
    media_random_off_fb: /MEDIA_RANDOM_OFF_FB/i,
    media_repeat_disc_on: /MEDIA_REPEAT_DISC_ON/i,
    media_repeat_disc_fb: /MEDIA_REPEAT_DISC_FB/i,
    media_repeat_track_on: /MEDIA_REPEAT_TRACK_ON/i,
    media_repeat_track_fb: /MEDIA_REPEAT_TRACK_FB/i,
    media_repeat_all_on: /MEDIA_REPEAT_ALL_ON/i,
    media_repeat_all_fb: /MEDIA_REPEAT_ALL_FB/i,
    media_repeat_off_on: /MEDIA_REPEAT_OFF_ON/i,
    media_repeat_off_fb: /MEDIA_REPEAT_OFF_FB/i,
    frame_fwd: /FRAME_FWD/i,
    frame_rev: /FRAME_REV/i,
    scan_speed: /SCAN_SPEED/i,

    // Source Selection
    source_tv1: /SOURCE_TV1/i,
    source_video1: /SOURCE_VIDEO1/i,
    source_video2: /SOURCE_VIDEO2/i,
    source_video3: /SOURCE_VIDEO3/i,
    source_tape1: /SOURCE_TAPE1/i,
    source_tape2: /SOURCE_TAPE2/i,
    source_cd1: /SOURCE_CD1/i,
    source_tuner1: /SOURCE_TUNER1/i,
    source_phono1: /SOURCE_PHONO1/i,
    source_aux1: /SOURCE_AUX1/i,
    source_cycle: /SOURCE_CYCLE/i,

    // Disc Controls
    disc_next: /DISC_NEXT/i,
    disc_prev: /DISC_PREV/i,
    disc_tray: /DISC_TRAY/i,
    disc_random: /DISC_RANDOM/i,
    disc_repeat: /DISC_REPEAT/i,
    disc_random_disc_on: /DISC_RANDOM_DISC_ON/i,
    disc_random_disc_fb: /DISC_RANDOM_DISC_FB/i,
    disc_random_all_on: /DISC_RANDOM_ALL_ON/i,
    disc_random_all_fb: /DISC_RANDOM_ALL_FB/i,
    disc_random_off_on: /DISC_RANDOM_OFF_ON/i,
    disc_random_off_fb: /DISC_RANDOM_OFF_FB/i,
    disc_repeat_disc_on: /DISC_REPEAT_DISC_ON/i,
    disc_repeat_disc_fb: /DISC_REPEAT_DISC_FB/i,
    disc_repeat_track_on: /DISC_REPEAT_TRACK_ON/i,
    disc_repeat_track_fb: /DISC_REPEAT_TRACK_FB/i,
    disc_repeat_all_on: /DISC_REPEAT_ALL_ON/i,
    disc_repeat_all_fb: /DISC_REPEAT_ALL_FB/i,
    disc_repeat_off_on: /DISC_REPEAT_OFF_ON/i,
    disc_repeat_off_fb: /DISC_REPEAT_OFF_FB/i,

    // Document Camera Controls
    doccam_light: /DOCCAM_LIGHT/i,
    doccam_lower_light_on: /DOCCAM_LOWER_LIGHT_ON/i,
    doccam_lower_light_fb: /DOCCAM_LOWER_LIGHT_FB/i,
    doccam_upper_light_on: /DOCCAM_UPPER_LIGHT_ON/i,
    doccam_upper_light_fb: /DOCCAM_UPPER_LIGHT_FB/i,

    // Picture Controls
    aspect_ratio: /ASPECT_RATIO/i,
    bright_up: /BRIGHT_UP/i,
    bright_dn: /BRIGHT_DN/i,
    color_up: /COLOR_UP/i,
    color_dn: /COLOR_DN/i,
    contrast_up: /CONTRAST_UP/i,
    contrast_dn: /CONTRAST_DN/i,
    sharp_up: /SHARP_UP/i,
    sharp_dn: /SHARP_DN/i,
    tint_up: /TINT_UP/i,
    tint_dn: /TINT_DN/i,
    pic_mute: /PIC_MUTE/i,
    pic_mute_on: /PIC_MUTE_ON/i,
    pic_mute_fb: /PIC_MUTE_FB/i,
    pic_freeze: /PIC_FREEZE/i,
    pic_freeze_on: /PIC_FREEZE_ON/i,
    pic_freeze_fb: /PIC_FREEZE_FB/i,

    // PIP Controls
    pip_pos: /PIP_POS/i,
    pip_swap: /PIP_SWAP/i,
    pip: /PIP/i,
    pip_on: /PIP_ON/i,
    pip_fb: /PIP_FB/i,

    // Audio Controls
    balance_up: /BALANCE_UP/i,
    balance_dn: /BALANCE_DN/i,
    bass_up: /BASS_UP/i,
    bass_dn: /BASS_DN/i,
    treble_up: /TREBLE_UP/i,
    treble_dn: /TREBLE_DN/i,
    loudness: /LOUDNESS/i,
    loudness_on: /LOUDNESS_ON/i,
    loudness_fb: /LOUDNESS_FB/i,

    // HVAC Controls
    hvac_cool_up: /HVAC_COOL_UP/i,
    hvac_cool_dn: /HVAC_COOL_DN/i,
    hvac_heat_up: /HVAC_HEAT_UP/i,
    hvac_heat_dn: /HVAC_HEAT_DN/i,
    hvac_humidify_up: /HVAC_HUMIDIFY_UP/i,
    hvac_humidify_dn: /HVAC_HUMIDIFY_DN/i,
    hvac_dehumidify_up: /HVAC_DEHUMIDIFY_UP/i,
    hvac_dehumidify_dn: /HVAC_DEHUMIDIFY_DN/i,
    hvac_hold_on: /HVAC_HOLD_ON/i,
    hvac_hold_fb: /HVAC_HOLD_FB/i,
    hvac_lock_on: /HVAC_LOCK_ON/i,
    hvac_lock_fb: /HVAC_LOCK_FB/i,
    hvac_fan: /HVAC_FAN/i,
    hvac_fan_on: /HVAC_FAN_ON/i,
    hvac_fan_on_fb: /HVAC_FAN_ON_FB/i,
    hvac_fan_auto: /HVAC_FAN_AUTO/i,
    hvac_fan_auto_fb: /HVAC_FAN_AUTO_FB/i,
    hvac_fan_status_fb: /HVAC_FAN_STATUS_FB/i,
    hvac_humidify_state: /HVAC_HUMIDIFY_STATE/i,
    hvac_state: /HVAC_STATE/i,
    hvac_auto: /HVAC_AUTO/i,
    hvac_auto_fb: /HVAC_AUTO_FB/i,
    hvac_cool: /HVAC_COOL/i,
    hvac_cool_fb: /HVAC_COOL_FB/i,
    hvac_heat: /HVAC_HEAT/i,
    hvac_heat_fb: /HVAC_HEAT_FB/i,
    hvac_off: /HVAC_OFF/i,
    hvac_off_fb: /HVAC_OFF_FB/i,
    hvac_eheat: /HVAC_EHEAT/i,
    hvac_eheat_fb: /HVAC_EHEAT_FB/i,
    hvac_cooling_fb: /HVAC_COOLING_FB/i,
    hvac_heating_fb: /HVAC_HEATING_FB/i,
    hvac_cooling2_fb: /HVAC_COOLING2_FB/i,
    hvac_eheating_fb: /HVAC_EHEATING_FB/i,
    hvac_humidify_auto: /HVAC_HUMIDIFY_AUTO/i,
    hvac_humidify_auto_fb: /HVAC_HUMIDIFY_AUTO_FB/i,
    hvac_dehumidify: /HVAC_DEHUMIDIFY/i,
    hvac_dehumidify_fb: /HVAC_DEHUMIDIFY_FB/i,
    hvac_humidify: /HVAC_HUMIDIFY/i,
    hvac_humidify_fb: /HVAC_HUMIDIFY_FB/i,
    hvac_humidify_off: /HVAC_HUMIDIFY_OFF/i,
    hvac_humidify_off_fb: /HVAC_HUMIDIFY_OFF_FB/i,
    hvac_dehumidifing_fb: /HVAC_DEHUMIDIFING_FB/i,
    hvac_humidifing_fb: /HVAC_HUMIDIFING_FB/i,

    // HVAC Levels
    hvac_cool_lvl: /HVAC_COOL_LVL/i,
    hvac_heat_lvl: /HVAC_HEAT_LVL/i,
    indoor_temp_lvl: /INDOOR_TEMP_LVL/i,
    outdoor_temp_lvl: /OUTDOOR_TEMP_LVL/i,
    indoor_humid_lvl: /INDOOR_HUMID_LVL/i,
    outdoor_humid_lvl: /OUTDOOR_HUMID_LVL/i,
    hvac_humidify_lvl: /HVAC_HUMIDIFY_LVL/i,
    hvac_dehumidify_lvl: /HVAC_DEHUMIDIFY_LVL/i,

    // Audio/Video Processor Levels
    bright_lvl: /BRIGHT_LVL/i,
    color_lvl: /COLOR_LVL/i,
    contrast_lvl: /CONTRAST_LVL/i,
    sharp_lvl: /SHARP_LVL/i,
    tint_lvl: /TINT_LVL/i,
    balance_lvl: /BALANCE_LVL/i,
    bass_lvl: /BASS_LVL/i,
    treble_lvl: /TREBLE_LVL/i,

    // Additional Controls
    surround_next: /SURROUND_NEXT/i,
    surround_prev: /SURROUND_PREV/i,
    cable_ab: /CABLE_AB/i,
    cable_b_on: /CABLE_B_ON/i,
    cable_b_fb: /CABLE_B_FB/i,

    // Projector Controls
    lamp_warming_fb: /LAMP_WARMING_FB/i,
    lamp_cooling_fb: /LAMP_COOLING_FB/i,
    lamp_power_fb: /LAMP_POWER_FB/i,

    // Motor Controls
    motor_stop: /MOTOR_STOP/i,
    motor_stop_fb: /MOTOR_STOP_FB/i,
    motor_open: /MOTOR_OPEN/i,
    motor_open_fb: /MOTOR_OPEN_FB/i,
    motor_close: /MOTOR_CLOSE/i,
    motor_close_fb: /MOTOR_CLOSE_FB/i,
    motor_preset: /MOTOR_PRESET/i,
    motor_pos_lvl: /MOTOR_POS_LVL/i,

    // Keypad Controls
    keypad_btn1: /KEYPAD_BTN1/i,
    keypad_btn1_fb: /KEYPAD_BTN1_FB/i,
    keypad_btn2: /KEYPAD_BTN2/i,
    keypad_btn2_fb: /KEYPAD_BTN2_FB/i,
    keypad_btn3: /KEYPAD_BTN3/i,
    keypad_btn3_fb: /KEYPAD_BTN3_FB/i,
    keypad_btn4: /KEYPAD_BTN4/i,
    keypad_btn4_fb: /KEYPAD_BTN4_FB/i,
    keypad_btn5: /KEYPAD_BTN5/i,
    keypad_btn5_fb: /KEYPAD_BTN5_FB/i,
    keypad_btn6: /KEYPAD_BTN6/i,
    keypad_btn6_fb: /KEYPAD_BTN6_FB/i,
    keypad_btn7: /KEYPAD_BTN7/i,
    keypad_btn7_fb: /KEYPAD_BTN7_FB/i,
    keypad_btn8: /KEYPAD_BTN8/i,
    keypad_btn8_fb: /KEYPAD_BTN8_FB/i,
    keypad_btn9: /KEYPAD_BTN9/i,
    keypad_btn9_fb: /KEYPAD_BTN9_FB/i,
    keypad_btn10: /KEYPAD_BTN10/i,
    keypad_btn10_fb: /KEYPAD_BTN10_FB/i,
    keypad_btn1_blink: /KEYPAD_BTN1_BLINK/i,
    keypad_btn1_blink_fb: /KEYPAD_BTN1_BLINK_FB/i,
    keypad_btn2_blink: /KEYPAD_BTN2_BLINK/i,
    keypad_btn2_blink_fb: /KEYPAD_BTN2_BLINK_FB/i,
    keypad_btn3_blink: /KEYPAD_BTN3_BLINK/i,
    keypad_btn3_blink_fb: /KEYPAD_BTN3_BLINK_FB/i,
    keypad_btn4_blink: /KEYPAD_BTN4_BLINK/i,
    keypad_btn4_blink_fb: /KEYPAD_BTN4_BLINK_FB/i,
    keypad_btn5_blink: /KEYPAD_BTN5_BLINK/i,
    keypad_btn5_blink_fb: /KEYPAD_BTN5_BLINK_FB/i,
    keypad_btn6_blink: /KEYPAD_BTN6_BLINK/i,
    keypad_btn6_blink_fb: /KEYPAD_BTN6_BLINK_FB/i,
    keypad_btn7_blink: /KEYPAD_BTN7_BLINK/i,
    keypad_btn7_blink_fb: /KEYPAD_BTN7_BLINK_FB/i,
    keypad_btn8_blink: /KEYPAD_BTN8_BLINK/i,
    keypad_btn8_blink_fb: /KEYPAD_BTN8_BLINK_FB/i,
    keypad_btn9_blink: /KEYPAD_BTN9_BLINK/i,
    keypad_btn9_blink_fb: /KEYPAD_BTN9_BLINK_FB/i,
    keypad_btn10_blink: /KEYPAD_BTN10_BLINK/i,
    keypad_btn10_blink_fb: /KEYPAD_BTN10_BLINK_FB/i,

    // Pool/Spa Controls
    pool_heat: /POOL_HEAT/i,
    spa_heat: /SPA_HEAT/i,
    spa_jets: /SPA_JETS/i,
    pool_heat_up: /POOL_HEAT_UP/i,
    pool_heat_dn: /POOL_HEAT_DN/i,
    spa_heat_up: /SPA_HEAT_UP/i,
    spa_heat_dn: /SPA_HEAT_DN/i,
    pool_pump_on: /POOL_PUMP_ON/i,
    pool_pump_fb: /POOL_PUMP_FB/i,
    spa_pump_on: /SPA_PUMP_ON/i,
    spa_pump_fb: /SPA_PUMP_FB/i,
    pool_light_on: /POOL_LIGHT_ON/i,
    pool_light_fb: /POOL_LIGHT_FB/i,
    spa_light_on: /SPA_LIGHT_ON/i,
    spa_light_fb: /SPA_LIGHT_FB/i,
    pool_heat_off: /POOL_HEAT_OFF/i,
    pool_heat_off_fb: /POOL_HEAT_OFF_FB/i,
    pool_heater: /POOL_HEATER/i,
    pool_heater_fb: /POOL_HEATER_FB/i,
    pool_solar: /POOL_SOLAR/i,
    pool_solar_fb: /POOL_SOLAR_FB/i,
    pool_solar_pref: /POOL_SOLAR_PREF/i,
    pool_solar_pref_fb: /POOL_SOLAR_PREF_FB/i,
    spa_heat_off: /SPA_HEAT_OFF/i,
    spa_heat_off_fb: /SPA_HEAT_OFF_FB/i,
    spa_heater: /SPA_HEATER/i,
    spa_heater_fb: /SPA_HEATER_FB/i,
    spa_solar: /SPA_SOLAR/i,
    spa_solar_fb: /SPA_SOLAR_FB/i,
    spa_solar_pref: /SPA_SOLAR_PREF/i,
    spa_solar_pref_fb: /SPA_SOLAR_PREF_FB/i,
    spa_jets_off: /SPA_JETS_OFF/i,
    spa_jets_off_fb: /SPA_JETS_OFF_FB/i,
    spa_jets_lo: /SPA_JETS_LO/i,
    spa_jets_lo_fb: /SPA_JETS_LO_FB/i,
    spa_jets_med: /SPA_JETS_MED/i,
    spa_jets_med_fb: /SPA_JETS_MED_FB/i,
    spa_jets_hi: /SPA_JETS_HI/i,
    spa_jets_hi_fb: /SPA_JETS_HI_FB/i,
    spa_blower_on: /SPA_BLOWER_ON/i,
    spa_blower_fb: /SPA_BLOWER_FB/i,
    pool_heating: /POOL_HEATING/i,
    pool_heating_solar: /POOL_HEATING_SOLAR/i,
    spa_heating: /SPA_HEATING/i,
    spa_heating_solar: /SPA_HEATING_SOLAR/i,
    pool_heat_lvl: /POOL_HEAT_LVL/i,
    spa_heat_lvl: /SPA_HEAT_LVL/i,
    pool_temp_lvl: /POOL_TEMP_LVL/i,
    spa_temp_lvl: /SPA_TEMP_LVL/i,

    // Video Conference Controls
    vconf_privacy: /VCONF_PRIVACY/i,
    vconf_privacy_on: /VCONF_PRIVACY_ON/i,
    vconf_privacy_fb: /VCONF_PRIVACY_FB/i,
    vconf_train: /VCONF_TRAIN/i,

    // Slide Controls
    slide_next: /SLIDE_NEXT/i,
    slide_prev: /SLIDE_PREV/i,

    // Multi Window Controls
    multiwin_preset: /MULTIWIN_PRESET/i,
    pan_up: /PAN_UP/i,
    pan_dn: /PAN_DN/i,

    // Sensor Controls
    sensor_fb: /SENSOR_FB/i,
    sensor_value: /SENSOR_VALUE/i,

    // Video Processor Controls
    vproc_preset: /VPROC_PRESET/i,

    // Weather Controls
    weather_force_reading: /WEATHER_FORCE_READING/i,
    weather_raining: /WEATHER_RAINING/i,
    weather_freezing: /WEATHER_FREEZING/i,
    weather_bar_rising: /WEATHER_BAR_RISING/i,
    weather_bar_falling: /WEATHER_BAR_FALLING/i,

    // Weather Levels
    weather_hi_temp_lvl: /WEATHER_HI_TEMP_LVL/i,
    weather_lo_temp_lvl: /WEATHER_LO_TEMP_LVL/i,
    weather_wind_chill_lvl: /WEATHER_WIND_CHILL_LVL/i,
    weather_heat_index_lvl: /WEATHER_HEAT_INDEX_LVL/i,
    weather_dewpoint_lvl: /WEATHER_DEWPOINT_LVL/i,
    weather_bar_lvl: /WEATHER_BAR_LVL/i,

    // Deprecated Constants
    menu_audio_menu: /MENU_AUDIO_MENU/i,
    menu_advanced: /MENU_ADVANCED/i,
    hvac_hold: /HVAC_HOLD/i,
    hvac_lock: /HVAC_LOCK/i,

    // Command/Param Constants
    duet_max_cmd_len: /DUET_MAX_CMD_LEN/i,
    duet_max_param_len: /DUET_MAX_PARAM_LEN/i,
    duet_max_hdr_len: /DUET_MAX_HDR_LEN/i,
    duet_ramping_repeat: /DUET_RAMPING_REPEAT/i,
};
