/**
 * @file NetLinx UnicodeLib.axi for tree-sitter
 * @license MIT
 */

module.exports = {
    constants: {
        __unicode_lib_version__: /__UNICODE_LIB_VERSION__/i,
        wc_format_ascii: /WC_FORMAT_ASCII/i,
        wc_format_unicode: /WC_FORMAT_UNICODE/i,
        wc_format_unicode_be: /WC_FORMAT_UNICODE_BE/i,
        wc_format_utf8: /WC_FORMAT_UTF8/i,
        wc_format_tp: /WC_FORMAT_TP/i,
        wc_max_string_size: /WC_MAX_STRING_SIZE/i,
        wc_max_g3_str_length: /WC_MAX_G3_STR_LENGTH/i,
        wc_max_g4_str_length: /WC_MAX_G4_STR_LENGTH/i,
    },
    variables: {
        cwc_upper_lookup: /cWcUpperLookup/i,
        cwc_upper_result: /cWcUpperResult/i,
        cwc_lower_lookup: /cWcLowerLookup/i,
        cwc_lower_result: /cWcLowerResult/i,
    },
    functions: {
        wc_encode: /WC_ENCODE/i,
        wc_decode: /WC_DECODE/i,
        _wc: /_WC/i,
        wc_to_ch: /WC_TO_CH/i,
        ch_to_wc: /CH_TO_WC/i,
        wc_find_string: /WC_FIND_STRING/i,
        wc_left_string: /WC_LEFT_STRING/i,
        wc_length_string: /WC_LENGTH_STRING/i,
        wc_lower_string: /WC_LOWER_STRING/i,
        wc_max_length_string: /WC_MAX_LENGTH_STRING/i,
        wc_mid_string: /WC_MID_STRING/i,
        wc_remove_string: /WC_REMOVE_STRING/i,
        wc_right_string: /WC_RIGHT_STRING/i,
        wc_set_length_string: /WC_SET_LENGTH_STRING/i,
        wc_upper_string: /WC_UPPER_STRING/i,
        wc_compare_string: /WC_COMPARE_STRING/i,
        wc_get_buffer_char: /WC_GET_BUFFER_CHAR/i,
        wc_get_buffer_string: /WC_GET_BUFFER_STRING/i,
        wc_concat_string: /WC_CONCAT_STRING/i,
        __wc_explode_file_handle: /__WC_EXPLODE_FILE_HANDLE/i,
        __wc_compose_file_handle: /__WC_COMPOSE_FILE_HANDLE/i,
        __wc_get_file_header: /__WC_GET_FILE_HEADER/i,
        __wc_get_file_format: /__WC_GET_FILE_FORMAT/i,
        wc_file_open: /WC_FILE_OPEN/i,
        wc_file_close: /WC_FILE_CLOSE/i,
        wc_file_read: /WC_FILE_READ/i,
        wc_file_read_line: /WC_FILE_READ_LINE/i,
        wc_file_write: /WC_FILE_WRITE/i,
        wc_file_write_line: /WC_FILE_WRITE_LINE/i,
        wc_tp_encode: /WC_TP_ENCODE/i,
    },
};
