PROGRAM_NAME='combined_definitions'

DEFINE_DEVICE
dvTP = 10001:1:0
dvTP2 = 10002:1:0

DEFINE_CONSTANT
// Define button constants
INTEGER SOURCE_1_BTN = 1
INTEGER SOURCE_2_BTN = 2
INTEGER SOURCE_3_BTN = 3
INTEGER POWER_BTN = 10

DEFINE_MUTUALLY_EXCLUSIVE
([dvTP,SOURCE_1_BTN],[dvTP,SOURCE_2_BTN],[dvTP,SOURCE_3_BTN])
([dvTP2,1]..[dvTP2,5])

DEFINE_LATCHING
[dvTP,POWER_BTN]
SOURCE_TOGGLE_BTN

DEFINE_TOGGLING
[dvTP,20]
[dvTP,21]
