#IF_NOT_DEFINED __SNAPI_CONST__
#DEFINE __SNAPI_CONST__

#IF_NOT_DEFINED DUET_MAX_CMD_LEN
DUET_MAX_CMD_LEN       = 1000
#END_IF

#IF_NOT_DEFINED DUET_MAX_PARAM_LEN
DUET_MAX_PARAM_LEN     = 100
#END_IF

#IF_NOT_DEFINED DUET_MAX_HDR_LEN
DUET_MAX_HDR_LEN       = 100
#END_IF

#END_IF
