name: Lint

on:
  push:
    paths:
      - "**/*.js"

  pull_request:
    paths:
      - "**/*.js"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint
